### ISSUE TITLE
process manifest

### ISSUE THREAD

**Issue by odinuv** [keboola/processor-select-columns#1]
manifest file has to be updated with the selected columns

**Comment by ondrejhlavacek** [comment]
~maybe not required? will be effectively replaced by https://github.com/keboola/processor-create-manifest~ spletl jsem si issue s https://github.com/keboola/processor-headers/issues/1

**Comment by ondrejhlavacek** [comment]
@odin co kdybych to místo doplňování manifestu sem celý přepsal? chtěl bych, aby to mělo config v JSONu, výběr sloupců jako pole místo stringu. udělám benchmark, jestli je rychlejší to parsovat pomocí `CsvFile`, `q` nebo `csvtool`.

**Comment by odinuv** [comment]
nj, csvtool bude asi blbe pracovat s manifestem

**Comment by ondrejhlavacek** [comment]
`csvtool` s manifestem pracovat vůbec nebude, bude tam klasická php appka, co pustí command s `csvtool`em.

 + podpora pro slicovaný soubory

**Comment by odinuv** [comment]
aha, no tak to by fakt chtelo ten benchmark jesli ma smysl se zalamovat s csv toolem, ale jako jo, v soucasnym stavu je to asi hodne raw
